sudo: required
jobs:
  include:
  - stage: frontend
    name: frontend build
    language: node_js
    node_js:
    - 10.15.3
    before_script:
    - cd frondend/spark
    - npm install -g @angular/cli
    - npm install --save-dev @angular-devkit/build-angular
    script:
    - ng build
notifications:
  email: false
